---
- name: Install Vim (Yum)
  become: yes
  become_user: root
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'
  with_items:
    - vim-enhanced.x86_64

- name: Add neovim ppa 
  become: yes
  become_user: root
  apt_repository: repo="ppa:neovim-ppa/unstable" state=present
  when: ansible_pkg_mgr == 'apt'

- name: Install Vim (Apt)
  become: yes
  become_user: root
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'
  with_items:
    - neovim
    - shellcheck
    - vim

- name: Create Development Directory
  file: path={{ dev_directory }} state=directory

- name: Checkout dotfiles repository
  git: repo=https://github.com/{{ github_account }}/dotfiles.git dest={{ dev_directory }}/dotfiles accept_hostkey=True

- name: Make install script executable
  file: path={{ dev_directory }}/dotfiles/install_dotfiles.sh mode=755

- name: Execute install script
  shell: "{{ dev_directory }}/dotfiles/install_dotfiles.sh"
  args:
    creates: ~/.vimrc
