---
- name: Install Vim (Yum)
  become: yes
  become_user: root
  yum: 
    name: vim-enhanced.x86_64
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'

- name: Install Vim (Apt)
  become: yes
  become_user: root
  apt: 
    pkg: vim
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Create Development Directory
  file: path={{ dev_directory }} state=directory

- name: Checkout dotfiles repository
  git: repo=https://github.com/{{ github_account }}/dotfiles.git dest={{ dev_directory }}/dotfiles accept_hostkey=True

- name: Make install script executable
  file: path={{ dev_directory }}/dotfiles/install_dotfiles.sh mode=755

- name: Execute install script
  shell: "{{ dev_directory }}/dotfiles/install_dotfiles.sh"
  args:
    creates: ~/.vimrc
